### ISSUE TITLE
Build rspamd with jemalloc allocator [default: OFF]

### ISSUE THREAD

**Issue by denji** [hardware/debian-mail-overlay#2]
-DENABLE_JEMALLOC=ON \
	-DJEMALLOC_ROOT_DIR=/...jemalloc... \

**Comment by hardware** [comment]
Related to https://github.com/hardware/mailserver/issues/256 ?

**Comment by denji** [comment]
No, this question is separate and related to the rspamd build with the better memory allocator.

* https://rspamd.com/doc/faq.html#how-rspamd-packages-are-built

**Comment by denji** [comment]
@hardware We use packages jemalloc from debian package. I'm not sure what to write the root directory `JEMALLOC_ROOT_DIR `: https://github.com/vstakhov/rspamd/blob/1.7.7/CMakeLists.txt#L628-L633

JEMALLOC_ROOT_DIR=/usr
JEMALLOC_ROOT_DIR=/usr/local

**Comment by hardware** [comment]
https://github.com/vstakhov/rspamd-build-scripts/blob/66d65a03fe4dd848b3f5a50b4035b1e8468f4dde/rspamd.spec#L81
